export const rolesOptions = [
    {
        value: 'author',
        label: 'Author',
        color: 'success'
    },
    {
        value: 'admin',
        label: 'Admin',
        color: 'info'
    },
    {
        value: 'superadmin',
        label: 'Superadmin',
        color: 'error'
    },
    {
        value: 'user',
        label: 'User',
        color: 'neutral'
    },
    {
        value: 'moderator',
        label: 'Moderator',
        color: 'warning'
    },
];

// export const usersListt = [
//     {
//         user_id: 1,
//         name: "Chiquita Flament",
//         avatar: "/images/200x200.png",
//         age: 39,
//         email: "cflament0@foxnews.com",
//         phone: "312-329-5963",
//         "licence":"a",
//         role: "author",
//         status: false,
//     },
//     {
//         user_id: 2,
//         name: "Ludvig Kennea",
//         avatar: "/images/200x200.png",
//         age: 55,
//         email: "lkennea1@nydailynews.com",
//         phone: "398-181-0799",
//         role: "admin",
//         status: false,
//     },
//     {
//         user_id: 3,
//         name: "Kelvin Keuning",
//         avatar: "/images/200x200.png",
//         age: 57,
//         email: "kkeuning2@nih.gov",
//         phone: "177-302-1065",
//         role: "admin",
//         status: true,
//     },
//     {
//         user_id: 4,
//         name: "Homere O'Noulane",
//         avatar: "/images/200x200.png",
//         age: 23,
//         email: "honoulane3@goo.ne.jp",
//         phone: "673-942-1852",
//         role: "author",
//         status: true,
//     },
//     {
//         user_id: 5,
//         name: "Kriste Salerno",
//         avatar: null,
//         age: 29,
//         email: "ksalerno4@amazonaws.com",
//         phone: "355-451-1490",
//         role: "author",
//         status: true,
//     },
//     {
//         user_id: 6,
//         name: "Georgianna Lancett",
//         avatar: "/images/200x200.png",
//         age: 26,
//         email: "glancett5@w3.org",
//         phone: "957-842-2732",
//         role: "author",
//         status: false,
//     },
//     {
//         user_id: 7,
//         name: "Elissa Hunter",
//         avatar: "/images/200x200.png",
//         age: 45,
//         email: "ehunter6@cocolog-nifty.com",
//         phone: "791-332-3620",
//         role: "superadmin",
//         status: false,
//     },
//     {
//         user_id: 8,
//         name: "Melvin Fynan",
//         avatar: null,
//         age: 51,
//         email: "mfynan7@photobucket.com",
//         phone: "231-966-7454",
//         role: "superadmin",
//         status: false,
//     },
//     {
//         user_id: 9,
//         name: "Cooper Hanfrey",
//         avatar: "/images/200x200.png",
//         age: 30,
//         email: "chanfrey8@indiatimes.com",
//         phone: "853-318-1593",
//         role: "admin",
//         status: true,
//     },
//     {
//         user_id: 10,
//         name: "Isobel Beininck",
//         avatar: null,
//         age: 20,
//         email: "ibeininck9@smugmug.com",
//         phone: "952-500-0727",
//         role: "user",
//         status: false,
//     },
//     {
//         user_id: 11,
//         name: "Arlen Guyonneau",
//         avatar: "/images/200x200.png",
//         age: 52,
//         email: "aguyonneaua@apple.com",
//         phone: "173-834-9691",
//         role: "admin",
//         status: true,
//     },
//     {
//         user_id: 12,
//         name: "Erda Matyja",
//         avatar: "/images/200x200.png",
//         age: 58,
//         email: "ematyjab@sbwire.com",
//         phone: "762-437-1668",
//         role: "superadmin",
//         status: true,
//     },
//     {
//         user_id: 13,
//         name: "Lacee Lant",
//         avatar: null,
//         age: 47,
//         email: "llantc@printfriendly.com",
//         phone: "672-524-9193",
//         role: "superadmin",
//         status: false,
//     },
//     {
//         user_id: 14,
//         name: "Louis Aireton",
//         avatar: "/images/200x200.png",
//         age: 35,
//         email: "lairetond@sphinn.com",
//         phone: "328-901-9864",
//         role: "admin",
//         status: true,
//     },
//     {
//         user_id: 15,
//         name: "Gilbertine Cocking",
//         avatar: null,
//         age: 52,
//         email: "gcockinge@dailymotion.com",
//         phone: "766-382-7120",
//         role: "user",
//         status: false,
//     },
//     {
//         user_id: 16,
//         name: "Mollee Knok",
//         avatar: null,
//         age: 44,
//         email: "mknokf@sourceforge.net",
//         phone: "783-114-6535",
//         role: "admin",
//         status: false,
//     },
//     {
//         user_id: 17,
//         name: "Vassily Littleover",
//         avatar: null,
//         age: 44,
//         email: "vlittleoverg@youtu.be",
//         phone: "306-137-7570",
//         role: "user",
//         status: false,
//     },
//     {
//         user_id: 18,
//         name: "Helenka Durkin",
//         avatar: null,
//         age: 28,
//         email: "hdurkinh@123-reg.co.uk",
//         phone: "846-295-1853",
//         role: "user",
//         status: true,
//     },
//     {
//         user_id: 19,
//         name: "Tirrell Gurry",
//         avatar: null,
//         age: 48,
//         email: "tgurryi@cnbc.com",
//         phone: "113-905-7580",
//         role: "author",
//         status: false,
//     },
//     {
//         user_id: 20,
//         name: "Reggie Kerridge",
//         avatar: "/images/200x200.png",
//         age: 41,
//         email: "rkerridgej@skyrock.com",
//         phone: "409-808-6660",
//         role: "user",
//         status: true,
//     },
//     {
//         user_id: 21,
//         name: "Carmita Mongan",
//         avatar: "/images/200x200.png",
//         age: 60,
//         email: "cmongank@posterous.com",
//         phone: "846-701-0107",
//         role: "user",
//         status: true,
//     },
//     {
//         user_id: 22,
//         name: "Auguste Guthrie",
//         avatar: "/images/200x200.png",
//         age: 60,
//         email: "aguthriel@ted.com",
//         phone: "806-371-3370",
//         role: "author",
//         status: false,
//     },
//     {
//         user_id: 23,
//         name: "Winthrop Melmeth",
//         avatar: "/images/200x200.png",
//         age: 26,
//         email: "wmelmethm@twitpic.com",
//         phone: "756-342-9975",
//         role: "moderator",
//         status: true,
//     },
//     {
//         user_id: 24,
//         name: "Estella Sorrill",
//         avatar: null,
//         age: 59,
//         email: "esorrilln@rakuten.co.jp",
//         phone: "648-531-8813",
//         role: "moderator",
//         status: true,
//     },
//     {
//         user_id: 25,
//         name: "Kippy Karlolak",
//         avatar: "/images/200x200.png",
//         age: 38,
//         email: "kkarlolako@chron.com",
//         phone: "328-832-0258",
//         role: "admin",
//         status: false,
//     },
//     {
//         user_id: 26,
//         name: "Carlye Castelli",
//         avatar: "/images/200x200.png",
//         age: 35,
//         email: "ccastellip@japanpost.jp",
//         phone: "604-192-0864",
//         role: "moderator",
//         status: false,
//     },
//     {
//         user_id: 27,
//         name: "Guillema Suddell",
//         avatar: null,
//         age: 18,
//         email: "gsuddellq@arstechnica.com",
//         phone: "143-446-3583",
//         role: "admin",
//         status: false,
//     },
//     {
//         user_id: 28,
//         name: "Florencia Turbill",
//         avatar: null,
//         age: 22,
//         email: "fturbillr@bloglines.com",
//         phone: "320-398-8190",
//         role: "superadmin",
//         status: true,
//     },
//     {
//         user_id: 29,
//         name: "Ches Douglass",
//         avatar: "/images/200x200.png",
//         age: 50,
//         email: "cdouglasss@mac.com",
//         phone: "415-987-8675",
//         role: "user",
//         status: false,
//     },
//     {
//         user_id: 30,
//         name: "Alethea Edgington",
//         avatar: "/images/200x200.png",
//         age: 30,
//         email: "aedgingtont@tripadvisor.com",
//         phone: "879-605-2310",
//         role: "superadmin",
//         status: false,
//     },
//     {
//         user_id: 31,
//         name: "Dawn Halley",
//         avatar: "/images/200x200.png",
//         age: 35,
//         email: "dhalleyu@utexas.edu",
//         phone: "643-436-4116",
//         role: "admin",
//         status: true,
//     },
//     {
//         user_id: 32,
//         name: "Philip MacNab",
//         avatar: null,
//         age: 50,
//         email: "pmacnabv@sakura.ne.jp",
//         phone: "807-224-4843",
//         role: "moderator",
//         status: false,
//     },
//     {
//         user_id: 33,
//         name: "Ibbie Labell",
//         avatar: "/images/200x200.png",
//         age: 42,
//         email: "ilabellw@hao123.com",
//         phone: "719-451-9510",
//         role: "moderator",
//         status: true,
//     },
//     {
//         user_id: 34,
//         name: "Willey Schneidau",
//         avatar: "/images/200x200.png",
//         age: 37,
//         email: "wschneidaux@google.nl",
//         phone: "251-366-1204",
//         role: "admin",
//         status: true,
//     },
//     {
//         user_id: 35,
//         name: "Brandi Brodbin",
//         avatar: "/images/200x200.png",
//         age: 33,
//         email: "bbrodbiny@booking.com",
//         phone: "430-467-6118",
//         role: "admin",
//         status: false,
//     },
//     {
//         user_id: 36,
//         name: "Sunny Disney",
//         avatar: "/images/200x200.png",
//         age: 51,
//         email: "sdisneyz@free.fr",
//         phone: "564-679-6640",
//         role: "user",
//         status: false,
//     },
//     {
//         user_id: 37,
//         name: "Olympe Willas",
//         avatar: "/images/200x200.png",
//         age: 59,
//         email: "owillas10@usa.gov",
//         phone: "141-706-4911",
//         role: "admin",
//         status: true,
//     },
//     {
//         user_id: 38,
//         name: "Eliza Ablett",
//         avatar: null,
//         age: 21,
//         email: "eablett11@independent.co.uk",
//         phone: "626-407-1753",
//         role: "user",
//         status: false,
//     },
//     {
//         user_id: 39,
//         name: "Pauly Jeannard",
//         avatar: "/images/200x200.png",
//         age: 53,
//         email: "pjeannard12@bbb.org",
//         phone: "967-125-5392",
//         role: "user",
//         status: true,
//     },
//     {
//         user_id: 40,
//         name: "Valli Charlin",
//         avatar: null,
//         age: 25,
//         email: "vcharlin13@economist.com",
//         phone: "586-965-9018",
//         role: "author",
//         status: true,
//     },
//     {
//         user_id: 41,
//         name: "Brita Ruppel",
//         avatar: null,
//         age: 25,
//         email: "bruppel14@china.com.cn",
//         phone: "678-460-7683",
//         role: "superadmin",
//         status: false,
//     },
//     {
//         user_id: 42,
//         name: "Toddie Pettifor",
//         avatar: "/images/200x200.png",
//         age: 56,
//         email: "tpettifor15@last.fm",
//         phone: "512-556-2086",
//         role: "superadmin",
//         status: true,
//     },
//     {
//         user_id: 43,
//         name: "Maryanne Commusso",
//         avatar: null,
//         age: 18,
//         email: "mcommusso16@unblog.fr",
//         phone: "802-989-9660",
//         role: "author",
//         status: true,
//     },
//     {
//         user_id: 44,
//         name: "Luce Khomishin",
//         avatar: "/images/200x200.png",
//         age: 44,
//         email: "lkhomishin17@google.com",
//         phone: "723-942-8991",
//         role: "author",
//         status: true,
//     },
//     {
//         user_id: 45,
//         name: "Corby Annies",
//         avatar: "/images/200x200.png",
//         age: 28,
//         email: "cannies18@ask.com",
//         phone: "912-274-3211",
//         role: "superadmin",
//         status: true,
//     },
//     {
//         user_id: 46,
//         name: "Vinnie Ellesworthe",
//         avatar: "/images/200x200.png",
//         age: 23,
//         email: "vellesworthe19@google.de",
//         phone: "211-436-3837",
//         role: "superadmin",
//         status: false,
//     },
//     {
//         user_id: 47,
//         name: "Gilberto Learmouth",
//         avatar: "/images/200x200.png",
//         age: 34,
//         email: "glearmouth1a@fema.gov",
//         phone: "623-142-0108",
//         role: "moderator",
//         status: false,
//     },
//     {
//         user_id: 48,
//         name: "Karena Garz",
//         avatar: "/images/200x200.png",
//         age: 49,
//         email: "kgarz1b@eventbrite.com",
//         phone: "529-871-4655",
//         role: "admin",
//         status: false,
//     },
//     {
//         user_id: 49,
//         name: "Jeramie Reuben",
//         avatar: "/images/200x200.png",
//         age: 47,
//         email: "jreuben1c@icq.com",
//         phone: "707-431-6926",
//         role: "user",
//         status: false,
//     },
//     {
//         user_id: 50,
//         name: "Lilllie Schankelborg",
//         avatar: "/images/200x200.png",
//         age: 56,
//         email: "lschankelborg1d@canalblog.com",
//         phone: "618-462-9053",
//         role: "superadmin",
//         status: true,
//     },
//     {
//         user_id: 51,
//         name: "Milton Dumbreck",
//         avatar: "/images/200x200.png",
//         age: 21,
//         email: "mdumbreck1e@netscape.com",
//         phone: "590-465-5097",
//         role: "author",
//         status: false,
//     },
//     {
//         user_id: 52,
//         name: "Abelard Surgen",
//         avatar: null,
//         age: 18,
//         email: "asurgen1f@cornell.edu",
//         phone: "598-724-9422",
//         role: "superadmin",
//         status: true,
//     },
//     {
//         user_id: 53,
//         name: "Maggi Kloisner",
//         avatar: "/images/200x200.png",
//         age: 35,
//         email: "mkloisner1g@icq.com",
//         phone: "263-343-4109",
//         role: "author",
//         status: true,
//     },
//     {
//         user_id: 54,
//         name: "Sashenka Barneville",
//         avatar: "/images/200x200.png",
//         age: 38,
//         email: "sbarneville1h@dot.gov",
//         phone: "493-126-3160",
//         role: "moderator",
//         status: true,
//     },
//     {
//         user_id: 55,
//         name: "Wilfred Ick",
//         avatar: null,
//         age: 25,
//         email: "wick1i@indiegogo.com",
//         phone: "197-184-9851",
//         role: "admin",
//         status: true,
//     },
//     {
//         user_id: 56,
//         name: "Carlyle Jermey",
//         avatar: "/images/200x200.png",
//         age: 33,
//         email: "cjermey1j@smh.com.au",
//         phone: "440-757-2456",
//         role: "user",
//         status: true,
//     },
//     {
//         user_id: 57,
//         name: "Yvon Gook",
//         avatar: null,
//         age: 28,
//         email: "ygook1k@ezinearticles.com",
//         phone: "539-299-3129",
//         role: "moderator",
//         status: false,
//     },
//     {
//         user_id: 58,
//         name: "Annecorinne Niles",
//         avatar: "/images/200x200.png",
//         age: 45,
//         email: "aniles1l@sohu.com",
//         phone: "778-490-6226",
//         role: "user",
//         status: false,
//     },
//     {
//         user_id: 59,
//         name: "Coleen Brosio",
//         avatar: null,
//         age: 29,
//         email: "cbrosio1m@java.com",
//         phone: "902-763-0233",
//         role: "superadmin",
//         status: false,
//     },
//     {
//         user_id: 60,
//         name: "Oralee Yeeles",
//         avatar: "/images/200x200.png",
//         age: 18,
//         email: "oyeeles1n@dailymail.co.uk",
//         phone: "178-665-0171",
//         role: "author",
//         status: false,
//     },
//     {
//         user_id: 61,
//         name: "Mignonne Debling",
//         avatar: null,
//         age: 21,
//         email: "mdebling1o@vistaprint.com",
//         phone: "873-777-8805",
//         role: "user",
//         status: true,
//     },
//     {
//         user_id: 62,
//         name: "Sterling Guittet",
//         avatar: "/images/200x200.png",
//         age: 40,
//         email: "sguittet1p@meetup.com",
//         phone: "594-492-1312",
//         role: "superadmin",
//         status: false,
//     },
//     {
//         user_id: 63,
//         name: "Teirtza Ivan",
//         avatar: "/images/200x200.png",
//         age: 58,
//         email: "tivan1q@mapy.cz",
//         phone: "879-905-0764",
//         role: "moderator",
//         status: true,
//     },
//     {
//         user_id: 64,
//         name: "Livy Bresner",
//         avatar: "/images/200x200.png",
//         age: 33,
//         email: "lbresner1r@typepad.com",
//         phone: "828-354-3958",
//         role: "moderator",
//         status: false,
//     },
//     {
//         user_id: 65,
//         name: "Debee Streeten",
//         avatar: "/images/200x200.png",
//         age: 42,
//         email: "dstreeten1s@businesswire.com",
//         phone: "203-327-1795",
//         role: "author",
//         status: true,
//     },
//     {
//         user_id: 66,
//         name: "Cordelie Longworth",
//         avatar: null,
//         age: 34,
//         email: "clongworth1t@fotki.com",
//         phone: "821-332-9179",
//         role: "user",
//         status: true,
//     },
//     {
//         user_id: 67,
//         name: "Livy Drinkhill",
//         avatar: "/images/200x200.png",
//         age: 21,
//         email: "ldrinkhill1u@ucoz.ru",
//         phone: "874-466-7074",
//         role: "superadmin",
//         status: true,
//     },
//     {
//         user_id: 68,
//         name: "Janna Neve",
//         avatar: "/images/200x200.png",
//         age: 39,
//         email: "jneve1v@merriam-webster.com",
//         phone: "459-485-8466",
//         role: "author",
//         status: true,
//     },
//     {
//         user_id: 69,
//         name: "Mark Miere",
//         avatar: "/images/200x200.png",
//         age: 57,
//         email: "mmiere1w@usa.gov",
//         phone: "160-366-1746",
//         role: "user",
//         status: false,
//     },
//     {
//         user_id: 70,
//         name: "Brandtr MacComiskey",
//         avatar: "/images/200x200.png",
//         age: 34,
//         email: "bmaccomiskey1x@independent.co.uk",
//         phone: "225-221-7368",
//         role: "author",
//         status: false,
//     },
//     {
//         user_id: 71,
//         name: "Danell Edmans",
//         avatar: "/images/200x200.png",
//         age: 30,
//         email: "dedmans1y@jimdo.com",
//         phone: "144-479-1265",
//         role: "moderator",
//         status: false,
//     },
//     {
//         user_id: 72,
//         name: "Brandais Heijnen",
//         avatar: null,
//         age: 18,
//         email: "bheijnen1z@phpbb.com",
//         phone: "109-857-1772",
//         role: "admin",
//         status: true,
//     },
//     {
//         user_id: 73,
//         name: "Elie Lotterington",
//         avatar: "/images/200x200.png",
//         age: 55,
//         email: "elotterington20@webs.com",
//         phone: "274-145-8690",
//         role: "author",
//         status: true,
//     },
//     {
//         user_id: 74,
//         name: "Perice Latour",
//         avatar: "/images/200x200.png",
//         age: 55,
//         email: "platour21@hhs.gov",
//         phone: "172-621-7932",
//         role: "superadmin",
//         status: false,
//     },
//     {
//         user_id: 75,
//         name: "Fraser Rutherforth",
//         avatar: null,
//         age: 27,
//         email: "frutherforth22@chicagotribune.com",
//         phone: "325-740-8825",
//         role: "admin",
//         status: false,
//     },
//     {
//         user_id: 76,
//         name: "Lannie Kesper",
//         avatar: null,
//         age: 24,
//         email: "lkesper23@prnewswire.com",
//         phone: "839-817-5336",
//         role: "superadmin",
//         status: true,
//     },
//     {
//         user_id: 77,
//         name: "Aindrea Scotchmur",
//         avatar: "/images/200x200.png",
//         age: 19,
//         email: "ascotchmur24@webnode.com",
//         phone: "896-398-5498",
//         role: "superadmin",
//         status: false,
//     },
//     {
//         user_id: 78,
//         name: "Elmer Coller",
//         avatar: null,
//         age: 45,
//         email: "ecoller25@shop-pro.jp",
//         phone: "753-598-6297",
//         role: "superadmin",
//         status: true,
//     },
//     {
//         user_id: 79,
//         name: "Debera Penburton",
//         avatar: "/images/200x200.png",
//         age: 35,
//         email: "dpenburton26@ycombinator.com",
//         phone: "805-326-0313",
//         role: "admin",
//         status: false,
//     },
//     {
//         user_id: 80,
//         name: "Alana Cockshott",
//         avatar: null,
//         age: 44,
//         email: "acockshott27@reddit.com",
//         phone: "678-958-5079",
//         role: "superadmin",
//         status: true,
//     },
//     {
//         user_id: 81,
//         name: "Donnajean Lafee",
//         avatar: "/images/200x200.png",
//         age: 37,
//         email: "dlafee28@clickbank.net",
//         phone: "276-330-2340",
//         role: "user",
//         status: true,
//     },
//     {
//         user_id: 82,
//         name: "Tami Yearne",
//         avatar: "/images/200x200.png",
//         age: 49,
//         email: "tyearne29@webmd.com",
//         phone: "397-908-6375",
//         role: "user",
//         status: false,
//     },
//     {
//         user_id: 83,
//         name: "Lloyd Haresnaip",
//         avatar: "/images/200x200.png",
//         age: 19,
//         email: "lharesnaip2a@princeton.edu",
//         phone: "480-270-8562",
//         role: "author",
//         status: true,
//     },
//     {
//         user_id: 84,
//         name: "Alana Crighten",
//         avatar: "/images/200x200.png",
//         age: 24,
//         email: "acrighten2b@list-manage.com",
//         phone: "371-565-6206",
//         role: "author",
//         status: true,
//     },
//     {
//         user_id: 85,
//         name: "Donal Scarlet",
//         avatar: null,
//         age: 48,
//         email: "dscarlet2c@prlog.org",
//         phone: "587-305-2518",
//         role: "moderator",
//         status: false,
//     },
//     {
//         user_id: 86,
//         name: "Lorant O'Hern",
//         avatar: "/images/200x200.png",
//         age: 53,
//         email: "lohern2d@hc360.com",
//         phone: "642-871-2027",
//         role: "admin",
//         status: true,
//     },
//     {
//         user_id: 87,
//         name: "Dotti Portail",
//         avatar: "/images/200x200.png",
//         age: 28,
//         email: "dportail2e@ucsd.edu",
//         phone: "342-676-2341",
//         role: "superadmin",
//         status: false,
//     },
//     {
//         user_id: 88,
//         name: "Hobard Sommerton",
//         avatar: "/images/200x200.png",
//         age: 51,
//         email: "hsommerton2f@nps.gov",
//         phone: "685-855-1133",
//         role: "user",
//         status: false,
//     },
//     {
//         user_id: 89,
//         name: "Roxana Silversmidt",
//         avatar: "/images/200x200.png",
//         age: 27,
//         email: "rsilversmidt2g@drupal.org",
//         phone: "821-686-2509",
//         role: "user",
//         status: true,
//     },
//     {
//         user_id: 90,
//         name: "Ciel Chaudrelle",
//         avatar: "/images/200x200.png",
//         age: 44,
//         email: "cchaudrelle2h@virginia.edu",
//         phone: "808-971-3375",
//         role: "moderator",
//         status: false,
//     },
//     {
//         user_id: 91,
//         name: "Graham Owthwaite",
//         avatar: "/images/200x200.png",
//         age: 51,
//         email: "gowthwaite2i@theglobeandmail.com",
//         phone: "587-261-3367",
//         role: "admin",
//         status: false,
//     },
//     {
//         user_id: 92,
//         name: "Maud Sommerlie",
//         avatar: "/images/200x200.png",
//         age: 32,
//         email: "msommerlie2j@furl.net",
//         phone: "834-295-2599",
//         role: "user",
//         status: true,
//     },
//     {
//         user_id: 93,
//         name: "Syd Witnall",
//         avatar: null,
//         age: 58,
//         email: "switnall2k@go.com",
//         phone: "194-980-4239",
//         role: "superadmin",
//         status: true,
//     },
//     {
//         user_id: 94,
//         name: "Christiano Doe",
//         avatar: "/images/200x200.png",
//         age: 54,
//         email: "cdoe2l@qq.com",
//         phone: "879-737-3730",
//         role: "author",
//         status: false,
//     },
//     {
//         user_id: 95,
//         name: "Abby Nevett",
//         avatar: null,
//         age: 51,
//         email: "anevett2m@time.com",
//         phone: "848-171-9424",
//         role: "moderator",
//         status: false,
//     },
//     {
//         user_id: 96,
//         name: "Manfred Paviour",
//         avatar: "/images/200x200.png",
//         age: 30,
//         email: "mpaviour2n@bloomberg.com",
//         phone: "189-202-2166",
//         role: "author",
//         status: false,
//     },
//     {
//         user_id: 97,
//         name: "Yvonne Pealing",
//         avatar: null,
//         age: 41,
//         email: "ypealing2o@google.com.au",
//         phone: "930-301-6707",
//         role: "user",
//         status: false,
//     },
//     {
//         user_id: 98,
//         name: "Fredericka Kloska",
//         avatar: "/images/200x200.png",
//         age: 25,
//         email: "fkloska2p@github.io",
//         phone: "703-660-2387",
//         role: "admin",
//         status: true,
//     },
//     {
//         user_id: 99,
//         name: "Dmitri Faithfull",
//         avatar: "/images/200x200.png",
//         age: 59,
//         email: "dfaithfull2q@google.fr",
//         phone: "326-763-2104",
//         role: "admin",
//         status: true,
//     },
//     {
//         user_id: 100,
//         name: "Atlante Crichmer",
//         avatar: "/images/200x200.png",
//         age: 25,
//         email: "acrichmer2r@sohu.com",
//         phone: "146-355-2782",
//         role: "admin",
//         status: true,
//     },
// ];


export const usersListt = [
    {
        user_id: 1,
        name: "Tech Innovators Inc.",
        avatar: "/images/200x200.png",
        employeeCount: 250,
        email: "contact@techinnovators.com",
        phone: "415-555-0123",
        role: "partner",
        status: true,
        license: "Enterprise",
        age: 15, // âge de l'entreprise
        description: "Leader dans l'innovation technologique, spécialisé dans le développement de solutions cloud et d'intelligence artificielle pour les entreprises.",
        services: ["Cloud Computing", "AI Solutions", "IoT Services", "Cybersecurity", "Digital Transformation"]
    },
    {
        user_id: 1,
        name: "Global Solutions SA",
        avatar: "/images/200x200.png",
        employeeCount: 120,
        email: "info@globalsolutions.com",
        phone: "312-555-0234",
        role: "client",
        status: true,
        license: "Professional",
        age: 8,
        description: "Cabinet de conseil international offrant des services complets en stratégie d'entreprise et transformation digitale.",
        services: ["Consulting", "Digital Strategy", "Business Analytics", "Project Management"]
    },{
        user_id: 1,
        name: "EcoTech Systems",
        avatar: "/images/200x200.png",
        employeeCount: 75,
        email: "contact@ecotechsystems.com",
        phone: "650-555-0345",
        role: "supplier",
        status: false,
        license: "Standard",
        age: 5,
        description: "Pionnier des solutions technologiques durables, EcoTech Systems développe des infrastructures éco-responsables pour un avenir plus vert.",
        services: ["Énergie renouvelable", "Optimisation énergétique", "Gestion des déchets électroniques", "Smart Grids", "Technologies vertes"]
    },
    {
        user_id: 3,
        name: "Digital Dynamics",
        avatar: "/images/200x200.png",
        employeeCount: 180,
        email: "info@digitaldynamics.com",
        phone: "212-555-0456",
        role: "partner",
        status: true,
        license: "Enterprise",
        age: 12,
        description: "Expert en transformation numérique, Digital Dynamics accompagne les entreprises dans l'automatisation et l'intégration de solutions digitales avancées.",
        services: ["Développement SaaS", "Big Data Analytics", "Automatisation des processus", "Cloud hybride", "Consulting en stratégie digitale"]
    },
    {
        user_id: 5,
        name: "Smart Solutions Ltd",
        avatar: "/images/200x200.png",
        employeeCount: 95,
        email: "contact@smartsolutions.com",
        phone: "408-555-0567",
        role: "client",
        status: true,
        license: "Professional",
        age: 6,
        description: "Fournisseur de solutions intelligentes, Smart Solutions Ltd développe des logiciels innovants pour optimiser la gestion des entreprises.",
        services: ["ERP et CRM", "Développement d'applications mobiles", "Solutions e-commerce", "Sécurité informatique", "Automatisation des workflows"]
    }
    // ... vous pouvez continuer à ajouter d'autres entreprises selon vos besoins
];
// export const userList = [

//     {
//         user_id: 1,
//         name: "Chiquita Flament",
//         avatar: "/images/200x200.png",
//         age: 39,
//         email: "cflament0@foxnews.com",
//         phone: "312-329-5963",
//         role: "author",
//         status: false,
//     },
//     {
//         user_id: 3,
//         name: "Tech Innovators Inc.",
//         avatar: "/images/200x200.png",
//         // size: "Large",
//         email: "123 Tech Lane, Silicon Valley, CA",
//         // website: "www.techinnovators.com",
//         status: false,
//         phone: "312-329-5963",
//         role: "partner",
//         age: 45
//     },
//     // {
//     //     user_id: 2,
//     //     name: "Health Plus",
//     //     industry: "Healthcare",
//     //     size: "Medium",
//     //     email: "456 Health Blvd, Boston, MA",
//     //     avatar: "www.healthplus.org",
//     //     status: true,
//     //     phone: "312-329-5963",
//     //     role: "client",
//     //     members: [28, 29, 30]
//     // },
//     // {
//     //     user_id: 3,
//     //     name: "EduFuture",
//     //     industry: "Education",
//     //     size: "Small",
//     //     email: "789 Knowledge St, Austin, TX",
//     //     website: "www.edufuture.edu",
//     //     status: false,
//     //     role: "supplier",
//     //     phone: "312-329-5963",
//     //     age: 31,
//     // },
//     // {
//     //     user_id: 4,
//     //     name: "Green Earth",
//     //     industry: "Environmental Services",
//     //     size: "Medium",
//     //     address: "101 Green Way, Portland, OR",
//     //     website: "www.greenearth.org",
//     //     status: true,
//     //     role: "partner",
//     //     phone: "312-329-5963",
//     //     members: [34, 35, 36]
//     // },
//     // {
//     //     user_id: 5,
//     //     name: "Creative Minds",
//     //     industry: "Media",
//     //     size: "Small",
//     //     address: "202 Creativity Ave, New York, NY",
//     //     website: "www.creativeminds.com",
//     //     status: true,
//     //     phone: "312-329-5963",
//     //     role: "client",
//     //     age: 37
//     // },
//     // {
//     //     user_id: 6,
//     //     name: "BuildRight",
//     //     industry: "Construction",
//     //     size: "Large",
//     //     address: "303 Construct Rd, Chicago, IL",
//     //     website: "www.buildright.com",
//     //     status: false,
//     //     phone: "312-329-5963",
//     //     role: "supplier",
//     //     age: 40, 
//     // },
//     // {
//     //     user_id: 7,
//     //     name: "Foodie's Delight",
//     //     industry: "Food Services",
//     //     size: "Medium",
//     //     email: "404 Gourmet Blvd, San Francisco, CA",
//     //     website: "www.foodiesdelight.com",
//     //     status: true,
//     //     role: "partner",
//     //     age: 3
//     // },
//     // {
//     //     user_id: 8,
//     //     name: "AutoMasters",
//     //     industry: "Automotive",
//     //     size: "Large",
//     //     address: "505 Motor St, Detroit, MI",
//     //     website: "www.automasters.com",
//     //     status: true,
//     //     role: "client",
//     //     members: [46, 47, 48]
//     // },
//     // {
//     //     user_id: 9,
//     //     name: "Fashion Forward",
//     //     industry: "Fashion",
//     //     size: "Medium",
//     //     address: "606 Style Ave, Los Angeles, CA",
//     //     website: "www.fashionforward.com",
//     //     status: false,
//     //     role: "supplier",
//     //     members: [49, 50, 51]
//     // },
//     // {
//     //     user_id: 10,
//     //     name: "Legal Eagles",
//     //     industry: "Legal Services",
//     //     size: "Small",
//     //     address: "707 Justice Dr, Washington, DC",
//     //     website: "www.legaleagles.com",
//     //     status: true,
//     //     role: "partner",
//     //     members: [52, 53, 54]
//     // },
//     // {
//     //     user_id: 11,
//     //     name: "Travel Quest",
//     //     industry: "Travel & Tourism",
//     //     size: "Medium",
//     //     address: "808 Adventure Rd, Miami, FL",
//     //     website: "www.travelquest.com",
//     //     status: true,
//     //     role: "client",
//     //     members: [55, 56, 57]
//     // },
//     // {
//     //     user_id: 12,
//     //     name: "FinTech Solutions",
//     //     industry: "Finance",
//     //     size: "Large",
//     //     address: "909 Finance St, New York, NY",
//     //     website: "www.fintechsolutions.com",
//     //     status: false,
//     //     role: "supplier",
//     //     members: [58, 59, 60]
//     // },
//     // {
//     //     user_id: 13,
//     //     name: "Artisan Crafts",
//     //     industry: "Arts & Crafts",
//     //     size: "Small",
//     //     address: "1010 Craft Ln, Santa Fe, NM",
//     //     website: "www.artisancrafts.com",
//     //     status: true,
//     //     role: "partner",
//     //     members: [61, 62, 63]
//     // },
//     // {
//     //     user_id: 14,
//     //     name: "Wellness Center",
//     //     industry: "Health & Wellness",
//     //     size: "Medium",
//     //     address: "1111 Wellness Way, Boulder, CO",
//     //     website: "www.wellnesscenter.org",
//     //     status: true,
//     //     role: "client",
//     //     members: [64, 65, 66]
//     // },
//     // {
//     //     user_id: 15,
//     //     name: "NextGen Robotics",
//     //     industry: "Robotics",
//     //     size: "Large",
//     //     address: "1212 Robot Dr, Pittsburgh, PA",
//     //     website: "www.nextgenrobotics.com",
//     //     status: false,
//     //     role: "supplier",
//     //     members: [67, 68, 69]
//     // },
//     // {
//     //     user_id: 16,
//     //     name: "Oceanic Research",
//     //     industry: "Marine Biology",
//     //     size: "Medium",
//     //     address: "1313 Ocean Blvd, San Diego, CA",
//     //     website: "www.oceanicresearch.org",
//     //     status: true,
//     //     role: "partner",
//     //     members: [70, 71, 72]
//     // },
//     // {
//     //     user_id: 17,
//     //     name: "SkyHigh Airlines",
//     //     industry: "Aviation",
//     //     size: "Large",
//     //     address: "1414 Skyway, Atlanta, GA",
//     //     website: "www.skyhighairlines.com",
//     //     status: true,
//     //     role: "client",
//     //     members: [73, 74, 75]
//     // },
//     // {
//     //     user_id: 18,
//     //     name: "Urban Farms",
//     //     industry: "Agriculture",
//     //     size: "Small",
//     //     address: "1515 Farm Rd, Austin, TX",
//     //     website: "www.urbanfarms.com",
//     //     status: false,
//     //     role: "supplier",
//     //     members: [76, 77, 78]
//     // },
//     // {
//     //     user_id: 19,
//     //     name: "Bright Futures",
//     //     industry: "Non-Profit",
//     //     size: "Medium",
//     //     address: "1616 Hope St, Chicago, IL",
//     //     website: "www.brightfutures.org",
//     //     status: true,
//     //     role: "partner",
//     //     members: [79, 80, 81]
//     // },
//     // {
//     //     user_id: 20,
//     //     name: "Tech Solutions",
//     //     industry: "Technology",
//     //     size: "Large",
//     //     address: "1717 Solution Blvd, San Jose, CA",
//     //     website: "www.techsolutions.com",
//     //     status: true,
//     //     role: "client",
//     //     members: [82, 83, 84]
//     // },
//     // {
//     //     user_id: 21,
//     //     name: "HealthBridge",
//     //     industry: "Healthcare",
//     //     size: "Medium",
//     //     address: "1818 Medical Dr, Boston, MA",
//     //     website: "www.healthbridge.org",
//     //     status: false,
//     //     role: "supplier",
//     //     members: [85, 86, 87]
//     // },
//     // {
//     //     user_id: 22,
//     //     name: "EduTech",
//     //     industry: "Education",
//     //     size: "Small",
//     //     address: "1919 Learn St, Austin, TX",
//     //     website: "www.edutech.com",
//     //     status: true,
//     //     role: "partner",
//     //     members: [88, 89, 90]
//     // },
//     // {
//     //     user_id: 23,
//     //     name: "EcoPlanet",
//     //     industry: "Environmental Services",
//     //     size: "Medium",
//     //     address: "2020 Green Rd, Portland, OR",
//     //     website: "www.ecoplanet.org",
//     //     status: true,
//     //     role: "client",
//     //     members: [91, 92, 93]
//     // },
//     // {
//     //     user_id: 24,
//     //     name: "MediaWorks",
//     //     industry: "Media",
//     //     size: "Small",
//     //     address: "2121 Broadcast Ave, New York, NY",
//     //     website: "www.mediaworks.com",
//     //     status: false,
//     //     role: "supplier",
//     //     members: [94, 95, 96]
//     // },
//     // {
//     //     user_id: 25,
//     //     name: "ConstructPro",
//     //     industry: "Construction",
//     //     size: "Large",
//     //     address: "2222 Build St, Chicago, IL",
//     //     website: "www.constructpro.com",
//     //     status: true,
//     //     role: "partner",
//     //     members: [97, 98, 99]
//     // },
//     // {
//     //     user_id: 26,
//     //     name: "Gourmet Express",
//     //     industry: "Food Services",
//     //     size: "Medium",
//     //     address: "2323 Food Blvd, San Francisco, CA",
//     //     website: "www.gourmetexpress.com",
//     //     status: true,
//     //     role: "client",
//     //     members: [100, 25, 26]
//     // },
//     // {
//     //     user_id: 27,
//     //     name: "AutoTech",
//     //     industry: "Automotive",
//     //     size: "Large",
//     //     address: "2424 Car Dr, Detroit, MI",
//     //     website: "www.autotech.com",
//     //     status: false,
//     //     role: "supplier",
//     //     members: [27, 28, 29]
//     // },
//     // {
//     //     user_id: 28,
//     //     name: "StyleHub",
//     //     industry: "Fashion",
//     //     size: "Medium",
//     //     address: "2525 Fashion Ave, Los Angeles, CA",
//     //     website: "www.stylehub.com",
//     //     status: true,
//     //     role: "partner",
//     //     members: [30, 31, 32]
//     // },
//     // {
//     //     user_id: 29,
//     //     name: "LegalAdvise",
//     //     industry: "Legal Services",
//     //     size: "Small",
//     //     address: "2626 Law Dr, Washington, DC",
//     //     website: "www.legaladvise.com",
//     //     status: true,
//     //     role: "client",
//     //     members: [33, 34, 35]
//     // },
//     // {
//     //     user_id: 30,
//     //     name: "TravelEase",
//     //     industry: "Travel & Tourism",
//     //     size: "Medium",
//     //     address: "2727 Trip Rd, Miami, FL",
//     //     website: "www.travelease.com",
//     //     status: false,
//     //     role: "supplier",
//     //     members: [36, 37, 38]
//     // }
// ];